language: python
cache: pip
dist: xenial

sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install tox
script:
  - tox
